version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_NAME: pizzabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432'
    volumes:
      - pizzas-db:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      DB_NAME: pizzabase
      DB_USER: postgres
      DB_PASSWORD: admin
      FIREBASE_STORAGE_BUCKET: pizzabase-35ee7.appspot.com
    ports:
      - '3000'
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_API_ORIGIN: http://localhost:3000
        VITE_API_PATH: /api/v1/trpc
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - '3001:3000'
    depends_on:
      - server
volumes:
  pizzas-db:
